/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import calendar from "@offset-dev/strapi-calendar/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import scheduler from "@webbio/strapi-plugin-scheduler/strapi-admin";
import strapiGtmModule from "strapi-gtm-module/strapi-admin";
import emailDesigner from "strapi-plugin-email-designer/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import strapiStripe from "strapi-stripe/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    ckeditor: ckeditor,
    calendar: calendar,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    scheduler: scheduler,
    "strapi-gtm-module": strapiGtmModule,
    "email-designer": emailDesigner,
    "import-export-entries": importExportEntries,
    "strapi-stripe": strapiStripe,
  },
});
